@baseurl=http://localhost:8080

### get base url
GET {{baseurl}} 


### get all collections
GET {{baseurl}}/collections


### 
POST {{baseurl}}/collections
Content-Type: application/json

{
    "title": "Moving Humans",
    "updateFrequency": 1000,
    "description": "Data of moving humans",
    "itemType": "moving feature"
}

### get existing collection with id
GET {{baseurl}}/collections/moving_humans


### get non existing collection
GET {{baseurl}}/collections/non_existing_collection


### delete existing collection
DELETE {{baseurl}}/collections/moving_humans

### update existing collection
PUT {{baseurl}}/collections/moving_humans

{
    "title": "Moving Man",
    "updateFrequency": 100,
    "description": "Data of moving men",
    "itemType": "moving feature"
}


###
PUT {{baseurl}}/collections/non_existing_collection

{
    "title": "Moving Man",
    "updateFrequency": 100,
    "description": "Data of moving men",
    "itemType": "moving feature"
}


###
GET {{baseurl}}/collections/ships/items?x1=727083.3918905254&y1=6178304.059568562&x2=734285.367741&y2=6184257.964565&dateTime=2024-09-03 00:00:00%2B02,2024-09-03 2:10:00%2B02&limit=5&subTrajectory=false 