@baseurl=http://localhost:8080

### get base url
GET {{baseurl}}

### get all collections
GET {{baseurl}}/collections

### get existing collection with id
GET {{baseurl}}/collections/moving_humans

### get non existing collection
GET {{baseurl}}/collections/non_existing_collection

### get feature collection
GET {{baseurl}}/collections/ships/items?x1=727083.3918905254&y1=6178304.059568562&x2=734285.367741&y2=6184257.964565&dateTime=2024-09-03 00:00:00%2B02,2024-09-03 2:10:00%2B02&limit=2&subTrajectory=false

### get meta data about a feature
GET {{baseurl}}/collections/ships/items/25


### get movement about ship 2190047
GET {{baseurl}}/collections/ships/items/2190047/tgsequence?x1=727083.3918905254&y1=6178304.059568562&x2=734285.367741&y2=6184257.964565&dateTime=2024-09-03 00:00:00%2B02,2024-09-03 2:10:00%2B02&limit=2&subTrajectory=false

### get movement about ship 2190047 whitout BOX
GET {{baseurl}}/collections/ships/items/2190048/tgsequence?dateTime=2024-09-03 00:00:00%2B02,2024-09-03 2:10:00%2B02&limit=2&subTrajectory=false

### get movement about ship 25 whitout BOX
GET {{baseurl}}/collections/ships/items/25/tgsequence?dateTime=2024-09-03 00:00:00%2B02,2024-09-06 2:10:00%2B02&limit=2&subTrajectory=false

### get tproperties of a feature
GET  {{baseurl}}/collections/ships2/items/25/tproperties

### get movement about ship 2190047 whitout BOX in ships2
GET {{baseurl}}/collections/ships2/items/2190047/tgsequence?dateTime=2024-09-03 00:00:00%2B02,2024-09-06 2:10:00%2B02&limit=2&subTrajectory=false